#!/bin/bash

color="\e[1;33m"
clear="\e[m"
echo -e ${color}
#fortune | cowsay -f `ls -1 /usr/share/cowsay/cows/ | sort -R | head -1` -fortune
echo "$(fortune -a -s | cowsay -f `ls -1 /usr/share/cowsay/cows/ | sort -R | head -1` -n)"
figlet $(hostname) 
echo -e ${clear}
