#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

"$HOME/.config/polybar/forest/launch.sh"
"$HOME/.config/picom/launch.sh"

# for annoying beeping sounds
xset -b

# fix the cursor
xsetroot -cursor_name left_ptr &

# start imwheel
imwheel -k -b 45 &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

